### ISSUE TITLE
Where do I even begin?

### ISSUE THREAD

**Issue by Chiiruno** [siavash119/qtchan#11]
![qtchan](https://user-images.githubusercontent.com/30435868/34431361-2929c1a0-ec34-11e7-9216-5fcaedcabd15.jpg)

**Comment by wallace-aph** [comment]
RTFM

**Comment by herherher** [comment]
CTRL + L and then you type the board you wanna visit. Everything is explained in the readme.

**Comment by Chiiruno** [comment]
>having to read the fucking manual
>random CTRL + L shortcut to get to a prompt to visit a board
kind of gay tbh

**Comment by siavash119** [comment]
ctrl+L is a very common shortcut to focus the navigation bar in a web browser.
