### ISSUE TITLE
A small feature I request

### ISSUE THREAD

**Issue by The-Soulless** [siavash119/qtchan#12]
Middle click to close a tab

**Comment by herherher** [comment]
I second that. Not necessarily middle click, but a shortcut like that would be nice. :+1:

**Comment by siavash119** [comment]
okay sure; I'm also going to implement close child tabs shortcuts

**Comment by siavash119** [comment]
[middle-click closes tab; ctrl+k closes children](https://github.com/siavash119/qtchan/commit/58ff3be01eaabc2173e821acea9f2c9da41f917c)
