### ISSUE TITLE
You can't post anymore

### ISSUE THREAD

**Issue by The-Soulless** [siavash119/qtchan#13]
Qtchan only supports legacy captcha which is no longer supported by 4chan

**Comment by siavash119** [comment]
already? I'll implement captcha v2 I guess. It's a bit more complicated, but I've looked at it before and still should be able to do it without js.

**Comment by siavash119** [comment]
[works](https://github.com/siavash119/qtchan/commit/e5c3724fd162ad6b51d8eb71d6f5de706d4b24d2)

look at the readme for solving info. i'll probably put numbers overlaying the grid and maybe click support.
