### ISSUE TITLE
Feature Request: Extraflags support

### ISSUE THREAD

**Issue by maluhia** [siavash119/qtchan#14]
Hello,

Please add extraflags support, which allows anons to set and view state/provincial flags. The extension is open source:
https://github.com/flaghunters/Extra-Flags-for-4chan
![image](https://user-images.githubusercontent.com/33070562/36407046-21e601a6-15b0-11e8-933a-5655c991d1a9.png)

**Comment by siavash119** [comment]
will do when I do normal flag images and IDs, thanks. I'll have qtchan get and store all the flags locally.

**Comment by maluhia** [comment]
The userscript contacts the central server https://flagtism.drunkensailor.org/ to load which posts numbers have which extraflags set, via get_flags_api2.php and post_flag_api2.php, so I feel that this must be incorporated in the application somehow. On page load, the script pulls all applicable flags from the github repo. You can refer to the userscript itself for insight.

**Comment by siavash119** [comment]
yep, I looked at it; shouldn't be too difficult. I just did showing normal flags [btw](https://github.com/siavash119/qtchan/commit/9d809d547b9eee568919cd6dd17e097ced00f841)

**Comment by siavash119** [comment]
![2018-02-22-01 28 13--int-85807207- -- -extraflags-](https://user-images.githubusercontent.com/9459552/36495276-b5b39ca2-176f-11e8-9855-51753dbb09d5.png) how's this?

**Comment by siavash119** [comment]
[here you go.](https://github.com/siavash119/qtchan/commit/b92d53f69a5d2a3b5e9c91fbe31aa1a0ac2300c3) look at the comment for instructions.
