### ISSUE TITLE
Easier captcha

### ISSUE THREAD

**Issue by 4chenz** [siavash119/qtchan#17]
Why don't you set it up like the normal noscript captcha? (images lined up with the keypad) 
All you have to do is replace the numbers.
I did it for one of my applications but I can't write C++ so It would be easier for you to implement this.
7->0
8->1
9->2
4->3
5->4
6->5
1->6
2->7
3->8

**Comment by siavash119** [comment]
[okay](https://github.com/siavash119/qtchan/commit/a2854a3ad7f6144d43c3643aff0e0e06e4ffa99e); i'm getting verified when solving the captcha, but i'm getting bad gateway from 4chan atm: I'm assuming it's a temporary 4chan problem.
