### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by Nunoma** [siavash119/qtchan#19]
Hi, I've just downloaded this program about 15 minutes ago, and I have read all the instructions but I'm not getting anything to display.
I installed the AppImage on my system, Ubuntu 18.04, but when I enter a board, nothing shows up.
![screenshot from 2018-05-23 11-35-48](https://user-images.githubusercontent.com/1957670/40416426-88d8f0ba-5e7d-11e8-92a0-0a6cd8e72969.png)
![screenshot from 2018-05-23 11-35-51](https://user-images.githubusercontent.com/1957670/40416427-88f94752-5e7d-11e8-9fde-9c25d3b1dfea.png)
![screenshot from 2018-05-23 11-36-00](https://user-images.githubusercontent.com/1957670/40416428-891732d0-5e7d-11e8-8dfc-75587a0c5431.png)
I have attached the screenshots, to better show my situation.
I hope you can (help me) find and solve the problem quickly.
Thanks in advance

**Comment by Nunoma** [comment]
P.S.
The last of the three images shows the program after I have refreshed all pages via the 'Actions' menu.

**Comment by siavash119** [comment]
yes, I'm still not sure about the AppImage build. Can you try building from master?

**Comment by Nunoma** [comment]
I have built it using the instructions in the README.md, and I can confirm it is now working.
Also, I couldn't quite figure out how to install qt5, as I am still new to Linux as a whole, so I just used the command [sudo apt-get install qt5-default] before copying the exact steps in the instructions. Perhaps this would be useful to add to the readme?
And thanks for indeed solving this problem quickly.

**Comment by siavash119** [comment]
okay will do, glad to hear it works. I'll check the AppImage build for next time, too. If still possible, can you run the AppImage from terminal and show me the log, so I can see the problem?

**Comment by siavash119** [comment]
closing; i'll look at AppImage myself sometime
