### ISSUE TITLE
Seems to load nothing (Windows 10)

### ISSUE THREAD

**Issue by adolfintel** [siavash119/qtchan#2]
Hi, I saw you shilling this on /g/

I just tried it on Windows 10 but it doesn't load anything, not even the list of boards. I don't see any error, just this. Refreshing doesn't do anything.

![2017-12-25 09_58_57-qtchan](https://user-images.githubusercontent.com/16307689/34336802-7eebd4ac-e95a-11e7-8305-860ffea66329.png)

**Comment by siavash119** [comment]
Ctrl+l, type g, hit enter.

read the thread, read the manual, read the source

**Comment by adolfintel** [comment]
Argh, I'm such an idiot, I totally didn't see it.

You should add it to the menu though.

**Comment by siavash119** [comment]
No problem, I need to add more straightforward instructions in general.
