### ISSUE TITLE
Feature Request: Open thread from local archive

### ISSUE THREAD

**Issue by Donnie-B** [siavash119/qtchan#21]
Hi,
I see that all opened threads are automatically saved to local folder.
Is it possible to reload the saved threads from local folder even though it's already archived or deleted in the server?
Also, it would be nice if qtchan can also load from 4chan archive servers.

**Comment by siavash119** [comment]
press F8 to see your archive. it's not so great, yet, but it's there. open threads by clicking the thread image

**Comment by Donnie-B** [comment]
The archive is good for now, I think.
Closing the issue.
