### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by ibnuda** [siavash119/qtchan#22]
System: Archlinux

What I did: `makepkg -sci`

Result: fail miserably.

Expected: glorious 4chin compiled.

What I've done to succeed building this program:

- Changed `pkgver` from `0.1` to `0.100`: fail at checksum.
- Added `--skipchecksums` flag: fail at compilation.
- Not using `makepkg` and use the instructions at `README.md`: ok.

That's it. My report is done.

**Comment by a1lu** [comment]
This is issued by a new QT release. They don't include QAction in their headers.
You need commit 
https://github.com/siavash119/qtchan/commit/718abeee5cf4aca8c99b35b26f43909362a29ee6
to build from AUR, this commit is not released at the moment, so AUR build is broken until next release.

You could also use an older QT version, though.

**Comment by ibnuda** [comment]
Wait a minute. I only have one version of qt5. While `makepkg` fails to build, manual compilation works just fine.
How does that related to new qt version?

**Comment by a1lu** [comment]
If you use the build instructions from readme.md you build from master. In master the commit to fix this issue is included.
The AUR build is fixed to release v0.1. This release is broken in arch with the newer QT version until @siavash119 creates the next release.

**Comment by ibnuda** [comment]
god dammit. why didn't I think of that?

thanks, mate.

**Comment by Dialga** [comment]
why don't you submit a qtchan-git PKGBUILD to aur to track master?

**Comment by ibnuda** [comment]
no u

**Comment by siavash119** [comment]
sorry been away; yeah, last release does not compile with newest qt. i wanted to add some customization features before the next release but got busy. master should work fine.

**Comment by ibnuda** [comment]
thanks, mate. no worries. keep up with the good job.
