### ISSUE TITLE
Interface freezes upon viewing any thread

### ISSUE THREAD

**Issue by ambroshia** [siavash119/qtchan#33]
I have managed to compile qtchan via the instructions described in the README file (there were no errors during compilation, so I assume it must have compiled successfully), and I can run the application and view the catalogue for all boards and scroll through them. I am also able to open threads in the catalogue by clicking on their post number or via the 'o' key.

However, when I view the thread by clicking on it, or by switching to it via the ctrl + tab shortcut, the application freezes and does not recognise any further key or mouse inputs until I terminate it through the console.

The output in the console does not indicate that the program has encountered an error, and the last lines before the freeze is just the messages indicating the thumbnails have been downloaded.

I have tried to compile it under both KDE Neon and Debian GNU/Linux (on ubuntu and debian repositories, I was unable to find the packages qt5 and qt5-dev, but I believe that qt5-base was the right package for the base development files). I am unsure if this is due to a compilation error, since there were no errors with compiling.

**Comment by siavash119** [comment]
so it never starts working? it's frozen forever?

**Comment by ambroshia** [comment]
I don't know what I did, but I installed and uninstalled qt creator, and restarted the computer a few times, and now the compiled program works perfectly, there are no freezes or unresponsiveness now.
